window.PLAYBOOKS = [
  {
    id:'inbox-triage', number:'01', category:'Executive Support', title:'Inbox Triage & Priority Management',
    summary:'A repeatable system for sorting executive email into action, delegation, waiting, and reference without losing urgent items.',
    tags:['Inbox','Prioritization','Executive Support'],
    scenario:'A busy executive receives a high volume of email across clients, internal teams, vendors, and scheduling requests. The goal is to surface what needs attention without turning the inbox into another task list.',
    goal:'Create a predictable daily triage rhythm that protects urgent items, clarifies ownership, and reduces unnecessary executive review.',
    tools:'Outlook or Gmail, task manager, calendar, shared notes',
    workflow:['Scan for time-sensitive items, deadlines, client impact, financial risk, and executive-only decisions.','Classify each message as Action, Delegate, Waiting, Calendar, Reference, or Archive.','Draft responses for items that can be resolved with known context and flag anything requiring executive judgment.','Move delegated items into the task system with an owner, due date, and source link.','Add schedule-sensitive items directly to the calendar or scheduling queue.','Run a final unresolved-item check before closing triage.'],
    qa:['No urgent message remains unclassified.','Delegated work has a named owner and due date.','Drafts clearly separate facts from assumptions.','Calendar commitments match the source email.'],
    metrics:['Time to first triage','Open executive decisions','Overdue delegated items','Messages reopened because of missed context'],
    automation:['Auto-label newsletters and routine notifications.','Create task-manager actions from flagged emails.','Use templates for recurring scheduling and acknowledgment messages.']
  },
  {
    id:'meeting-prep', number:'02', category:'Executive Support', title:'Executive Meeting Prep Brief',
    summary:'A concise pre-meeting briefing workflow that gives the executive context, objectives, open decisions, and likely follow-ups before the call starts.',
    tags:['Meetings','Briefing','Preparation'],
    scenario:'The executive has back-to-back calls and needs useful context without rereading long email threads, notes, and project updates.',
    goal:'Deliver a short, decision-focused meeting brief that can be reviewed in under two minutes.',
    tools:'Calendar, email, CRM, meeting notes, task manager',
    workflow:['Confirm meeting objective, attendees, and expected outcome.','Review the latest email thread, CRM notes, prior meeting notes, and open tasks.','Pull forward unresolved commitments, blockers, and decisions.','Summarize context in three to five bullets using only what is relevant to the meeting.','List likely decisions or questions the executive may need to address.','Add post-meeting capture fields for actions, owners, and deadlines.'],
    qa:['No stale or contradicted information is presented as current.','Names, organizations, dates, and commitments are verified.','The brief separates context from required decisions.','The executive can understand the meeting objective at a glance.'],
    metrics:['Brief preparation time','Missing-context incidents','Action items captured after meeting','Executive follow-up requests'],
    automation:['Pull CRM fields into a briefing template.','Auto-generate attendee summaries from approved internal sources.','Create action placeholders before the meeting begins.']
  },
  {
    id:'calendar-management', number:'03', category:'Executive Support', title:'Calendar & Scheduling Workflow',
    summary:'A scheduling SOP for coordinating meetings, protecting focus time, resolving conflicts, and keeping the calendar decision-ready.',
    tags:['Calendar','Scheduling','Coordination'],
    scenario:'Scheduling requests arrive through email, chat, Calendly, and internal requests while the executive has limited availability.',
    goal:'Keep the calendar accurate, intentional, and conflict-free while minimizing scheduling back-and-forth.',
    tools:'Google Calendar or Outlook, Calendly, email, time-zone reference',
    workflow:['Confirm meeting type, required attendees, duration, and deadline.','Check protected focus blocks, travel, personal constraints, and existing commitments.','Offer the smallest useful set of time options instead of open-ended availability.','Confirm time zone and meeting location or virtual link.','Add agenda context and source links to the event.','Recheck conflicts and notify stakeholders immediately if conditions change.'],
    qa:['Time zone is explicit for cross-region meetings.','Buffer time is preserved where required.','No double-booking or hidden travel conflict exists.','Invite contains enough context for participants to prepare.'],
    metrics:['Scheduling turnaround time','Reschedule rate','Calendar conflicts','No-show rate'],
    automation:['Routing forms for common meeting types.','Automatic buffers and minimum-notice rules.','Reminder workflows for missing agendas or prework.']
  },
  {
    id:'ticket-escalation', number:'04', category:'Customer Experience', title:'Customer Support Escalation & Ownership',
    summary:'A structured escalation path for high-risk, repeated, or unresolved customer issues with clear handoffs and documentation.',
    tags:['Support','Escalation','SLA'],
    scenario:'A customer has an unresolved issue, repeated contacts, billing risk, or a situation that exceeds frontline authority.',
    goal:'Escalate the right cases quickly while preserving context, ownership, and customer communication.',
    tools:'Zendesk, LiveAgent, Help Scout, CRM, internal chat',
    workflow:['Review full ticket history before responding or escalating.','Classify severity using customer impact, financial risk, urgency, and policy exception.','Resolve immediately when the issue is within authority and evidence is complete.','Escalate with a concise internal summary, requested decision, supporting evidence, and deadline.','Tell the customer what happens next, who owns the case, and when to expect an update.','Track until resolution and close only after documentation and follow-up are complete.'],
    qa:['Escalation includes the exact decision needed.','Customer receives a clear next-update expectation.','Duplicate work is avoided by checking prior contacts.','Final resolution and root cause are documented.'],
    metrics:['Escalation rate','Time to resolution','Repeat contact rate','SLA breaches','CSAT after escalation'],
    automation:['Auto-tag repeat contacts and high-risk keywords.','SLA alerts before breach.','Escalation templates with required evidence fields.']
  },
  {
    id:'chargeback-workflow', number:'05', category:'Customer Experience', title:'Chargeback Evidence & Recovery Workflow',
    summary:'A defensible workflow for reviewing disputes, gathering evidence, contacting customers appropriately, and tracking outcomes.',
    tags:['Chargebacks','Payments','Evidence'],
    scenario:'A business receives payment disputes that require evidence collection, response deadlines, and better visibility into recurring causes.',
    goal:'Improve dispute handling consistency and create a reliable evidence trail without overpromising recoverability.',
    tools:'Stripe or payment processor, CRM, order system, support inbox, dispute tracker',
    workflow:['Log the dispute deadline, reason code, amount, and transaction identifiers.','Review order, fulfillment, communication, refund, and policy evidence.','Determine whether customer outreach is appropriate and document the result.','Build the evidence package in a standard order that directly answers the dispute reason.','Submit before the internal deadline, not the processor deadline.','Track outcome and categorize root cause for process improvement.'],
    qa:['Evidence directly supports the disputed transaction.','Dates and customer identifiers are consistent across systems.','Refund status is confirmed before submission.','Sensitive data is excluded unless required and permitted.'],
    metrics:['Dispute volume','Response timeliness','Win/loss rate','Preventable dispute reasons','Repeat customer disputes'],
    automation:['Deadline alerts.','Evidence checklist by reason code.','Auto-populated dispute tracker from processor exports.']
  },
  {
    id:'csat-recovery', number:'06', category:'Customer Experience', title:'CSAT Recovery Playbook',
    summary:'A service-recovery workflow for low-satisfaction cases that identifies root cause, fixes the issue, and turns feedback into operating data.',
    tags:['CSAT','Retention','Service Recovery'],
    scenario:'A customer leaves low feedback after an interaction or a support case shows clear signs of dissatisfaction.',
    goal:'Recover the relationship when possible while capturing actionable reasons behind the negative experience.',
    tools:'Help desk, CRM, survey tool, QA tracker',
    workflow:['Review the full case before contacting the customer.','Identify whether the issue was product, policy, communication, delay, or agent execution.','Correct any open operational issue first.','Send a concise recovery response that acknowledges the specific experience and next step.','Escalate product or policy patterns to the correct owner.','Record the root cause and recovery outcome for trend analysis.'],
    qa:['Response addresses the actual complaint rather than using a generic apology.','Open operational issues are not marked resolved prematurely.','Root-cause category is evidence-based.','Any promised follow-up has a named owner.'],
    metrics:['Low-CSAT rate','Recovery response time','Repeat complaints','Root-cause distribution','Post-recovery sentiment'],
    automation:['Low-score alerts.','Root-cause tagging suggestions.','Follow-up reminders for unresolved recovery cases.']
  },
  {
    id:'daily-ops-triage', number:'07', category:'Operations', title:'Daily Operations Triage',
    summary:'A lightweight operating rhythm for separating moving work, stuck work, and decisions that require leadership attention.',
    tags:['Operations','Priorities','Execution'],
    scenario:'A small remote team has work across multiple tools, owners, and deadlines, making it difficult to see what actually needs attention.',
    goal:'Create a short daily view of execution health without turning status reporting into a full meeting.',
    tools:'ClickUp, Asana, Notion, Slack or Teams',
    workflow:['Review due, overdue, blocked, and newly assigned work.','Group work into Moving, Stuck, and Needs You.','For stuck items, record blocker, owner, and next unblock action.','For leadership decisions, state the decision needed and the consequence of delay.','Remove noise that does not change the day’s execution.','Publish the triage summary and update owners as conditions change.'],
    qa:['Every stuck item has a clear blocker.','Decision requests are specific and answerable.','No duplicate tasks are reported as separate risks.','Completed work is removed from active triage.'],
    metrics:['Blocked work count','Average blocker age','Overdue tasks','Decision turnaround time'],
    automation:['Daily overdue-task digest.','Auto-flag tasks with no owner.','Escalation reminders when blocker age crosses a threshold.']
  },
  {
    id:'sop-framework', number:'08', category:'Operations', title:'SOP Creation Framework',
    summary:'A practical method for turning tribal knowledge into concise, testable, maintainable operating documentation.',
    tags:['SOPs','Documentation','Process Design'],
    scenario:'A recurring process depends on one person’s memory, contains inconsistent handoffs, or is difficult to train.',
    goal:'Create an SOP that another capable person can execute without unnecessary explanation.',
    tools:'Docs, Notion, Confluence, Loom, task manager',
    workflow:['Define the trigger and intended final state.','Map the process from start to finish before writing detailed instructions.','Separate routine actions from decision rules and exceptions.','Write atomic steps with one clear action per line.','Add QA checks at the point where errors are most expensive.','Test the SOP with someone who did not write it and revise based on failure points.'],
    qa:['Trigger and completion criteria are explicit.','Steps are executable rather than descriptive.','Exceptions are documented next to the relevant decision.','Owner and review cadence are visible.'],
    metrics:['Training questions','Execution errors','Time to competency','SOP revision frequency'],
    automation:['Version-review reminders.','Link forms, templates, and checklists directly in the relevant step.','Track SOP feedback through a simple issue log.']
  },
  {
    id:'process-audit', number:'09', category:'Operations', title:'Process Improvement Audit',
    summary:'A structured review for finding waste, handoff friction, duplicated work, automation candidates, and missing controls.',
    tags:['Audit','Improvement','Efficiency'],
    scenario:'A recurring process works, but it feels slower, more manual, or less reliable than it should be.',
    goal:'Identify concrete changes that simplify execution while preserving required controls and quality.',
    tools:'Workflow map, task data, interviews, spreadsheet, automation platform',
    workflow:['Map the current process exactly as performed, not as documented.','Mark waits, rework, approvals, duplicate entry, unclear ownership, and tool switching.','Separate required controls from legacy habits.','Score improvement ideas by impact, effort, risk, and reversibility.','Pilot the smallest useful change first.','Measure before and after, then update documentation and ownership.'],
    qa:['Recommendations are tied to observed process evidence.','Automation does not remove necessary human judgment.','Dependencies and failure modes are documented.','The revised process has a measurable success condition.'],
    metrics:['Cycle time','Handoffs','Rework rate','Manual touches','Error rate'],
    automation:['Form-to-task creation.','Status synchronization between systems.','Rule-based reminders and approvals.']
  },
  {
    id:'team-onboarding', number:'10', category:'Team Management', title:'Remote Team Onboarding',
    summary:'A structured first-week onboarding system covering access, role clarity, training, shadowing, practice, and readiness checks.',
    tags:['Onboarding','Training','Remote Teams'],
    scenario:'A new team member joins remotely and needs to become useful without relying on scattered messages or ad hoc shadowing.',
    goal:'Give new hires a clear path from access setup to supervised execution and independent ownership.',
    tools:'HR checklist, password manager, knowledge base, chat, LMS or docs',
    workflow:['Complete access, security, and communication setup before role training.','Explain role outcomes, responsibilities, escalation boundaries, and success metrics.','Assign required reading and process walkthroughs in a logical sequence.','Use shadowing followed by reverse-shadowing and supervised practice.','Review early work with a documented QA rubric.','Confirm readiness by task type instead of using tenure alone.'],
    qa:['Access is least-privilege and role appropriate.','Training materials match the current process.','Practice work has explicit feedback.','Readiness is documented before independent ownership.'],
    metrics:['Time to first independent task','Training completion','Early QA score','First-30-day error patterns'],
    automation:['Access checklist reminders.','Training completion tracking.','Automatic 7-day and 30-day manager check-ins.']
  },
  {
    id:'qa-scorecard', number:'11', category:'Team Management', title:'QA Scorecard & Coaching Loop',
    summary:'A fair QA system that turns sample reviews into actionable coaching without reducing quality to one score.',
    tags:['QA','Coaching','Performance'],
    scenario:'A support or operations team needs consistent quality review across multiple agents or task types.',
    goal:'Measure important behaviors, catch risk, and create a repeatable coaching loop tied to evidence.',
    tools:'QA form, help desk, spreadsheet or BI dashboard, coaching notes',
    workflow:['Define critical errors separately from coachable quality criteria.','Sample work using a consistent method instead of only reviewing obvious failures.','Score observable behavior and cite evidence.','Identify one or two priority coaching themes per review period.','Agree on a specific behavior change and practice plan.','Recheck similar work to confirm improvement.'],
    qa:['Rubric items are atomic and objectively observable.','Critical failures are not hidden by a high average score.','Reviewer notes cite the exact work being assessed.','Coaching actions are specific and measurable.'],
    metrics:['QA score','Critical error rate','Repeat coaching themes','Calibration variance','Improvement after coaching'],
    automation:['Randomized QA sampling.','Scorecard dashboards.','Alerts for repeated critical-failure categories.']
  },
  {
    id:'crm-data-hygiene', number:'12', category:'Systems & Automation', title:'CRM Data Hygiene & Automation Audit',
    summary:'A governance workflow for finding duplicate, incomplete, stale, and conflicting records before automating downstream processes.',
    tags:['CRM','Data Quality','Automation'],
    scenario:'Sales, service, and operations rely on CRM data, but inconsistent fields and duplicate records make reporting and automation unreliable.',
    goal:'Improve data trust before building more workflows on top of the system.',
    tools:'Salesforce, HubSpot, spreadsheet, integration platform',
    workflow:['Identify fields that drive reporting, routing, automation, and customer communication.','Profile missing values, duplicates, formatting inconsistencies, and conflicting sources.','Define the source of truth for each critical field.','Standardize field rules and merge criteria before bulk cleanup.','Clean a small test segment and validate downstream effects.','Add preventive controls so the same errors do not immediately return.'],
    qa:['No destructive merge occurs without a defined survivor rule.','Required fields match actual business needs.','Automation dependencies are tested after cleanup.','Data ownership is assigned for ongoing governance.'],
    metrics:['Duplicate rate','Required-field completeness','Sync failures','Manual corrections','Automation exceptions'],
    automation:['Duplicate detection rules.','Field validation.','Scheduled stale-record reports.','Integration-error alerts.']
  }
];
